config/routes.rb
ObsFactory::Engine.routes.draw do
  cons = { project: %r{[^\/]*} }
  get 'project/dashboard/:project' => "distributions#show", as: 'dashboard', constraints: cons
  get 'project/staging_projects/:project' => "staging_projects#index", as: 'staging_projects', constraints: cons
  get 'project/staging_projects/:project/:id' => "staging_projects#show", as: 'staging_project', constraints: cons

  # Used to enforce the refresh of the cache of jobs (using cache=refresh)
  get 'openqa_jobs' => 'openqa_jobs#index'

  # Compatibility with old build.opensuse.org routes
  old_mount_point = 'factory'
  get "#{old_mount_point}/dashboard", to: redirect('project/dashboard/openSUSE:Factory')
  get "#{old_mount_point}/staging_projects", to: redirect('project/staging_projects/openSUSE:Factory')
  get "#{old_mount_point}/staging_projects/:id", to: redirect('project/staging_projects/openSUSE:Factory/%{id}')
  get "#{old_mount_point}/openqa_jobs", to: redirect('openqa_jobs')
end

app/models/obs_factory/distribution.rb
require 'open-uri'

module ObsFactory
  
  class UnknownDistribution < Exception
  end
  
  # A Distribution. Contains a reference to the corresponding Project object.
  class Distribution
    include ActiveModel::Model
    extend ActiveModel::Naming
    extend Forwardable
    
    SOURCE_VERSION_FILE = "_product/openSUSE.product"
    RINGS_PREFIX = ":Rings"

    attr_accessor :project, :strategy

    def distribution_strategy_for_project(project)
      s = case project.name
        when 'openSUSE:Factory' then DistributionStrategyFactory.new
        when 'openSUSE:Factory:PowerPC' then DistributionStrategyFactoryPPC.new
        when /^openSUSE:.*/ then DistributionStrategyOpenSUSE.new
        when /^SUSE:SLE-12-SP\d:GA/ then DistributionStrategySLE12SP1.new
        when /^SUSE:SLE-15:GA/ then DistributionStrategySLE15.new
        when /^SUSE:SLE-12-SP.*CASP\d*/ then DistributionStrategyCasp.new
        else raise UnknownDistribution
      end
      s.project = project
      s
    end

    def initialize(project = nil)
      self.project = project
      self.strategy = distribution_strategy_for_project(project)
    end

    def self.attributes
      %w(name description staging_projects openqa_version openqa_group
      source_version totest_version published_version staging_manager
      standard_project live_project images_project ring_projects)
    end

    def attributes
      Hash[self.class.attributes.map { |a| [a, nil] }]
    end

    def_delegators :@strategy, :root_project_name, :url_suffix, :openqa_version,
                               :openqa_iso, :arch, :openqa_group, :staging_manager

    # Find a distribution by id
    #
    # @return [Distribution] the distribution
    def self.find(id)
      project = ::Project.find_by_name(id)
      if project
        begin
          Distribution.new(project)
        rescue UnknownDistribution
          nil
        end
      else
        nil
      end
    end

    # Name of the associated project
    #
    # @return [String] name of the Project object
    def name
      project.name
    end

    # Id of the distribution
    #
    # @return [String] name
    def id
      name
    end

    # Description of the associated project
    #
    # @return [String] description of the Project object
    def description
      project.description
    end

    # Version of the distribution used as ToTest
    #
    # @return [String] version string
    def totest_version
      Rails.cache.fetch("totest_version_for_#{name}", expires_in: 10.minutes) do
        strategy.totest_version
      end
    end

    # Version of the published distribution
    #
    # @return [String] version string
    def published_version
      Rails.cache.fetch("published_version_for_#{name}", expires_in: 10.minutes) do
        strategy.published_version
      end
    end

    # Staging projects associated to the distribution
    #
    # @return [Array] array of StagingProject objects
    def staging_projects
      @staging_projects ||= StagingProject.for(self)
    end

    # Staging projects associated to the distribution, including non-letter
    #
    # @return [Array] array of StagingProject objects
    def staging_projects_all
      @staging_projects ||= StagingProject.for(self, false)
    end

    # Staging project associated to the distribution and with the given id
    #
    # @param [String] id of the staging project
    # @return [StagingProject] the associated project or nil
    def staging_project(id)
      if @staging_projects
        @staging_projects.select {|p| p.id == id }
      else
        StagingProject.find(self, id)
      end
    end

    # Version of the distribution used as source
    #
    # @return [String] version string
    def source_version
      Rails.cache.fetch("source_version_for_#{name}", expires_in: 10.minutes) do
        begin
          p = Xmlhash.parse(ActiveXML::backend.direct_http "/source/#{name}/#{SOURCE_VERSION_FILE}?expand=1")
          p.get('products').get('product').get('version')
        rescue ActiveXML::Transport::NotFoundError
          nil
        end
      end
    end

    # openQA jobs related with a given version of the distribution
    #
    # @param [#to_s] version must be :source, :totest or :published
    # @return [Array] list of OpenqaJob objects
    def openqa_jobs_for(version)
      filter = {distri: 'opensuse', version: strategy.openqa_version, build: send(:"#{version}_version"), group: strategy.openqa_group}
      OpenqaJob.find_all_by(filter, exclude_modules: true)
    end

    # Requests with some open review targeting the distribution, filtered by
    # the group in charge of the open reviews
    #
    # @param [String] group name of the group
    # @return [Array] list of Request objects
    def requests_with_reviews_for_group(group)
      Request.with_open_reviews_for(by_group: group, target_project: root_project_name)
    end

    # Requests with some open review targeting the distribution, filtered by
    # the user in charge of the open reviews
    #
    # @param [String] user name of the user
    # @return [Array] list of Request objects
    def requests_with_reviews_for_user(user)
      Request.with_open_reviews_for(by_user: user, target_project: root_project_name)
    end

    # Standard project
    #
    # @return [ObsProject] standard
    def standard_project
      if @standard_project.nil?
        @standard_project = ObsProject.new(name, 'standard')
        @standard_project.exclusive_repository = 'standard'
      end
      @standard_project
    end

    # Live project
    #
    # @return [ObsProject] live
    def live_project
      if @live_project.nil?
        @live_project = ObsProject.new("#{name}:Live", 'live')
        if @live_project.project.nil?
          @live_project = nil
        else
          @live_project.exclusive_repository = 'images'
        end
      end
      @live_project
    end

    # Images project
    #
    # @return [ObsProject] images
    def images_project
      if @images_project.nil?
        @images_project = ObsProject.new(name, 'images')
        @images_project.exclusive_repository = 'images'
      end
      @images_project
    end

    # Projects defining the distribution rings
    #
    # @return [Array] list of ObsProject objects nicknamed with numbers
    def ring_projects
      @ring_projects ||= strategy.rings.each_with_index.map do |r,idx|
        ObsProject.new("#{rings_project_name}:#{idx}-#{r}", "#{idx}-#{r}")
      end
    end

    # Name of the project used as top-level for the ring projects
    #
    # @return [String] project name
    def rings_project_name
      "#{root_project_name}#{RINGS_PREFIX}"
    end

    # URL parameter for openqa's /test route to be opened in view
    # for given project
    #
    # @return [String] URL part (e.g. match=A)
    def openqa_filter(project)
      return strategy.openqa_filter(project)
    end

  end
end

app/models/obs_factory/distribution_strategy_casp.rb
module ObsFactory

  class DistributionStrategyCasp < DistributionStrategyFactory

    def casp_version
      match = project.name.match(/^SUSE:SLE-12-SP.*CASP(\d*)/ )
      match[1]
    end

    def staging_manager
      'caasp-staging-managers'
    end

    def repo_url
      'http://download.opensuse.org/distribution/13.2/repo/oss/media.1/build'
    end

    def openqa_version
      '1.0'
    end

    # Name of the ISO file by the given staging project tracked on openqa
    #
    # @return [String] file name
    def openqa_iso(project)
      project_iso(project)
    end

    # Name of the ISO file produced by the given staging project's Test-DVD
    #
    # Not part of the Strategy API, but useful for subclasses
    #
    # @return [String] file name
    def project_iso(project)
      arch = self.arch
      buildresult = Buildresult.find_hashed(project: project.name, package: "CAASP-dvd5-DVD-#{arch}",
                                            repository: 'images',
                                            view: 'binarylist')
      binaries = []
      # we get multiple architectures, but only one with binaries
      buildresult.elements('result') do |r|
        r['binarylist'].elements('binary') do |b|
          return b['filename'] if /\.iso$/ =~ b['filename']
        end
      end
      nil
    end

  end
end

app/models/obs_factory/distribution_strategy_factory_ppc.rb
module ObsFactory

  # PowerPC to Factory Diff
  class DistributionStrategyFactoryPPC < DistributionStrategyFactory

    def root_project_name
      "openSUSE:Factory"
    end

    def totest_version_file
      'images/local/_product:openSUSE-cd-mini-ppc64le'
    end

    def arch
      'ppc64le'
    end

    def url_suffix
      'ports/ppc/factory'
    end

    def openqa_group
      'openSUSE Tumbleweed PowerPC'
    end

    def repo_url
      'http://download.opensuse.org/ports/ppc/factory/repo/oss/media.1/build'
    end

    def published_arch
      "ppc64le"
    end
  end
end

app/models/obs_factory/distribution_strategy_opensuse.rb
module ObsFactory

  # this class tracks the differences between Factory and the upcoming release
  class DistributionStrategyOpenSUSE < DistributionStrategyFactory
    def opensuse_version
      # Remove the "openSUSE:" part
      project.name[9..-1]
    end

    def opensuse_leap_version
      # Remove the "openSUSE:Leap:" part
      project.name[14..-1]
    end

    def openqa_version
      opensuse_leap_version
    end

    def openqa_group
      "openSUSE Leap #{opensuse_leap_version}"
    end

    def repo_url
      "http://download.opensuse.org/distribution/leap/#{opensuse_leap_version}/repo/oss/media.1/media"
    end

    def url_suffix
      "distribution/leap/#{opensuse_leap_version}/iso"
    end

    def openqa_iso_prefix
      "openSUSE-#{opensuse_version}-Staging"
    end

    def published_arch
      'x86_64'
    end

    def test_dvd_prefix
      '000product:openSUSE-dvd5-dvd'
    end

    def totest_version_file
      'images/local/000product:openSUSE-cd-mini-x86_64'
    end

    # Version of the published distribution
    #
    # @return [String] version string
    def published_version
      begin
        f = open(repo_url)
      rescue OpenURI::HTTPError => e
        return 'unknown'
      end
      matchdata = %r{openSUSE-#{opensuse_leap_version}-#{published_arch}-Build(.*)}.match(f.read)
      matchdata[1]
    end

    # URL parameter for Leap
    def openqa_filter(project)
      return "match=#{opensuse_leap_version}:S:#{project.letter}"
    end

  end
end

app/models/obs_factory/distribution_strategy_sle12_sp1.rb
module ObsFactory

  class DistributionStrategySLE12SP1 < DistributionStrategyFactory

    def sp_version
      match = project.name.match(/SLE-12-(.*):GA/)
      match[1]
    end
 
    def staging_manager
      'sle-staging-managers'
    end

    def repo_url
      'http://download.opensuse.org/distribution/13.2/repo/oss/media.1/build'
    end

    def openqa_version
      "SLES 12 #{sp_version}"
    end

    # Name of the ISO file by the given staging project tracked on openqa
    #
    # @return [String] file name
    def openqa_iso(project)
      ending = project_iso(project)
      return if ending.nil?
      ending.gsub!(/.*-Build/, '')
      "SLE12-#{sp_version}-Staging:#{project.letter}-Test-Server-DVD-#{arch}-Build#{project.letter}.#{ending}"
    end

  end
end

app/controllers/obs_factory/application_controller.rb
module ObsFactory
  class ApplicationController < ::Webui::WebuiController
    layout 'obs_factory/application'

    rescue_from ObsFactory::OpenqaApi::OpenqaFailure do |ex|
      render text: "failure in openQA"
    end
  end
end

app/controllers/obs_factory/distributions_controller.rb
module ObsFactory
  class DistributionsController < ApplicationController
    respond_to :html

    before_action :require_distribution

    def require_distribution
      @distribution = Distribution.find(params[:project])
      unless @distribution
        redirect_to main_app.root_path, flash: { error: "#{params[:project]} is not a valid openSUSE distribution, can't offer dashboard" }
      end
    end
    
    def show
      @staging_projects = StagingProjectPresenter.sort(@distribution.staging_projects)
      @versions = { source: @distribution.source_version,
                    totest: @distribution.totest_version,
                    published: @distribution.published_version }
      @ring_prjs = ObsProjectPresenter.wrap(@distribution.ring_projects)
      @standard = ObsProjectPresenter.new(@distribution.standard_project)
      @live = @distribution.live_project
      @live = ObsProjectPresenter.new(@live) unless @live.nil?
      @images = ObsProjectPresenter.new(@distribution.images_project)
      @openqa_jobs = @distribution.openqa_jobs_for(:totest)
      calculate_reviews
      # For the breadcrumbs
      @project = @distribution.project
    end

    protected

    def calculate_reviews
      @reviews = {}
      @reviews[:review_team]  = @distribution.requests_with_reviews_for_group('opensuse-review-team').size
      @reviews[:factory_auto] = @distribution.requests_with_reviews_for_group('factory-auto').size
      @reviews[:legal_auto]   = @distribution.requests_with_reviews_for_group('legal-auto').size
      @reviews[:legal_team]   = @distribution.requests_with_reviews_for_group('legal-team').size
      @reviews[:repo_checker] = @distribution.requests_with_reviews_for_user('repo-checker').size
    end
  end
end

app/controllers/obs_factory/openqa_jobs_controller.rb
module ObsFactory
  class OpenqaJobsController < ApplicationController
    respond_to :json, :html

    def index
      @q = params[:q] || {}
      @cache = params[:cache]
      openqa_jobs = OpenqaJob.find_all_by(@q, cache: @cache)
      respond_to do |format|
        format.html { @openqa_jobs = OpenqaJobPresenter.wrap(openqa_jobs) }
        format.json { render json: openqa_jobs }
      end
    end
  end
end

app/controllers/obs_factory/staging_projects_controller.rb
module ObsFactory
  class StagingProjectsController < ApplicationController
    respond_to :json, :html

    before_action :require_distribution
    
    def require_distribution
      @distribution = Distribution.find(params[:project])
      unless @distribution
        redirect_to main_app.root_path, flash: { error: "#{params[:project]} is not a valid openSUSE distribution, can't offer dashboard" }
      end
    end

    def index
      respond_to do |format|
        format.html do
          @staging_projects = StagingProjectPresenter.sort(@distribution.staging_projects_all)
          @backlog_requests = Request.with_open_reviews_for(by_group: @distribution.staging_manager, target_project: @distribution.name)
          file = PackageFile.new(
            project_name: "#{params[:project]}:Staging",
            package_name: "dashboard",
            name: "ignored_requests")
          unless file.to_s.nil?
            @ignored_requests = YAML.load(file.to_s)
          end
          if !@ignored_requests.nil? and @ignored_requests
            @backlog_requests_ignored = @backlog_requests.select { |req| @ignored_requests.key?(req.number) }
            @backlog_requests = @backlog_requests.select { |req| !@ignored_requests.key?(req.number) }
            @backlog_requests_ignored.sort! { |x,y| x.package <=> y.package }
          else
            @backlog_requests_ignored = []
          end
          @backlog_requests.sort! { |x,y| x.package <=> y.package }
          # For the breadcrumbs
          @project = @distribution.project
        end
        format.json { render json: @distribution.staging_projects_all }
      end
    end

    before_action :require_id, only: [:show]

    def require_id
      @staging_project = StagingProject.find(@distribution, params[:id])
      unless @staging_project
        redirect_to main_app.root_path, flash: { error: "#{params[:id]} is not a valid staging project" }
      end
    end

    def show
      respond_to do |format|
        format.html do
          @staging_project = StagingProjectPresenter.new(@staging_project)
          # For the breadcrumbs
          @project = @distribution.project
        end
        format.json { render json: @staging_project }
      end
    end
  end
end

app/helpers/obs_factory/application_helper.rb
module ObsFactory
  module ApplicationHelper

    # Catch some url helpers used in the OBS layout and forward them to
    # the main application
    %w(root_path project_show_path search_path user_show_url user_show_path user_logout_path
       user_login_path user_register_user_path user_do_login_path news_feed_path project_toggle_watch_path
       project_list_public_path monitor_path projects_path new_project_path
       user_rss_notifications_url).each do |m|
      define_method(m) do |*args|
        main_app.send(m, *args)
      end
    end

    def openqa_links_helper
      OpenqaJob.openqa_links_url
    end

  end
end

app/views/obs_factory/staging_projects/_buildinfo.html.erb
<% ok = project.building_repositories.empty? -%>
<dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>Building repositories</dt>
<dd>
<% if ok %>
  None.
<% else %>
  <% building = project.building_repositories.map do |repo| %>
    <% link_to "#{repo['repository']}-#{repo['arch']} (#{repo['state']})".html_safe,
                main_app.project_repository_state_url(project.name, repo['repository']) %>
  <% end %>
  <%= building.to_sentence.html_safe %>
<% end %>
</dd>
<% ok = project.broken_packages.size.zero? -%>
<dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>Broken packages</dt>
<dd>
<% if ok %>
  None.
<% else %>
  <% broken = project.broken_packages.map do |pack| %>
    <% link_to "#{pack['package']} (#{pack['state']})".html_safe,
              main_app.package_show_url(project.name, pack['package']) %>
  <% end %>
  <%= broken.to_sentence.html_safe %>
<% end %>
</dd>
</dd>

app/views/obs_factory/staging_projects/_expand_collapse.js.erb
$('a.staging_expand').click(function() {
  var css = 'staging_'+$(this).data('name');
  $('.staging_expand.'+css).hide('appear');
  $('.staging_collapsible.'+css).show('slide');
  return false;
});
$('a.staging_collapse').click(function() {
  var css = 'staging_'+$(this).data('name');
  $('.staging_collapsible.'+css).hide('slide');
  $('.staging_expand.'+css).show('appear');
  return false;
});

app/views/obs_factory/staging_projects/_infos.html.haml
%div{class: "box box-shadow"}
  %h2{class: "box-header"} Infos

  %p Empty Projects:
  - empties = @staging_projects.select { |p| p.overall_state == :empty && p.name =~ /Staging:[A-Z]?$/ }
  - empties = empties.map { |p| link_to(p.letter, main_app.project_show_path(p.name)) }

  %p
    - if empties.empty?
      none
    - else
      = empties.sort.join(' &ndash; ').html_safe


  %p Backlog:
  - if @backlog_requests.empty?
    %p 
      %i Empty
  - else
    %ul{class: "staging_backlog"}
      - @backlog_requests.each_with_index do |req,counter|
        %li
          = link_to elide(req.package, length = 19), main_app.request_show_path(req.number)
        - if counter > 5 && @backlog_requests.size > counter + 1
          %li ... #{@backlog_requests.size - counter} more
          - break

  - if @backlog_requests_ignored.present?
    %p Ignored:
    %ul{class: "staging_backlog_ignored"}
      - @backlog_requests_ignored.each_with_index do |req,counter|
        %li
          = link_to elide(req.package, length = 19), main_app.request_show_path(req.number), title: @ignored_requests[req.number]
        - if counter > 5 && @backlog_requests_ignored.size > counter + 1
          %li ... #{@backlog_requests_ignored.size - counter} more
          - break

app/views/obs_factory/staging_projects/_legend.html.haml
%div{class: "box box-shadow", id: "legends"}
  %h2{class: "box-header"} Legend

  %p Requests
  %ul{class: "color-legend"}
    %li
      %span{class: "ok"}
      Ready
    %li
      %span{class: "review"}
      In review
    %li
      %span{class: "obsolete"}
      Obsolete
    %li
      %span{class: "untracked"}
      Untracked
    %li{class: "delete"}
      %span{class: "delete"}
      Delete

  %p Projects
  %ul{class: "color-legend"}
    %li
      %span{class: "staging-project state-building"}
      Building
    %li
      %span{class: "staging-project state-testing"}
      Testing
    %li
      %span{class: "staging-project state-review"}
      Review
    %li
      %span{class: "staging-project state-acceptable"}
      Acceptable
    %li
      %span{class: "staging-project state-unacceptable"}
      Unacceptable
    %li
      %span{class: "staging-project state-failed"}
      Failed

  %p Reviews
  %ul{class: "color-legend"}
    %li
      %i{class: "fa fa-#{ObsFactory::StagingProjectPresenter.review_icon('opensuse-review-team')}"}
      = link_to 'Source Review', main_app.group_show_path('opensuse-review-team')
    %li
      %i{class: "fa fa-#{ObsFactory::StagingProjectPresenter.review_icon('repo-checker')}"}
      = link_to 'Installation Check', main_app.user_show_path('repo-checker')
    %li
      %i{class: "fa fa-#{ObsFactory::StagingProjectPresenter.review_icon('legal-team')}"}
      = link_to 'Legal Review', main_app.group_show_path('legal-team')

app/views/obs_factory/staging_projects/_openqa_jobs.html.erb
<% ok = project.openqa_jobs.all? {|j| j.result == 'passed' } -%>
<dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>openQA Jobs</dt>
<dd>
<% if project.openqa_jobs.empty? %>
  None.
<% else %>
  <ul>
    <% project.openqa_jobs.each do |job| %>
      <li class="openqa_job"><%= render job %></li>
    <% end %>
  </ul>
<% end %>
</dd>

app/views/obs_factory/staging_projects/_overall_state.html.haml
%div{class: "overall-state staging-project state-#{project.overall_state}"}
  %div{class: 'letter'}
    = link_to project.letter, staging_project_path(project: @distribution.name, id: project.id)
  %div{class: 'state'}
    = link_to project.overall_state, main_app.project_show_path(project.name)
  %div{class: 'progress'}
    - if project.overall_state == :building
      - progress = project.build_progress
      = link_to main_app.project_monitor_url(progress[:subproject]) do
        = "#{progress[:percentage]}%"
    - elsif project.overall_state == :review
      = "#{project.review_percentage}%"
    - elsif project.overall_state == :testing
      = link_to "#{openqa_links_helper}/tests?hoursfresh=24&#{@distribution.openqa_filter(project)}" do
        = "#{project.testing_percentage}%"
  - if project.meta['splitter_info']
    %div{class: 'splitter-info', title: 'strategy information (name, group)'}
      - splitter_info = project.meta['splitter_info']
      %div{class: 'splitter-info-strategy'}
        = "#{splitter_info['strategy']['name']}"
      %div{class: 'splitter-info-group'}
        = "#{splitter_info['group']}"

app/views/obs_factory/staging_projects/_packages_list.html.haml
%ul{class: "packages-list"}
  - max = 15
  - count = project.classified_requests.count
  - if count <= max+1 # Prevent the "1 more" link
    = render partial: "request", collection: project.classified_requests
  - else
    = render partial: "request", collection: project.classified_requests[0,max]
    - name = project.letter
    %li.request= link_to "...#{count - max} more", "#", class: "staging_expand staging_#{name}", data: {name: name}
    %div{class: "staging_collapsible staging_#{name}", style: "display:none"}
      = render partial: "request", collection: project.classified_requests[max..-1]
      %li.request= link_to "collapse", "#", class: "staging_collapse", data: {name: name}

app/views/obs_factory/staging_projects/_request.html.haml
%li{class: "#{request[:css]} #{request[:request_type]} request"}
  = link_to request[:package], main_app.request_show_path(request[:number])
  - mrs = request[:missing_reviews] || []
  - mrs.each do |mr|
    = link_to content_tag(:i, nil, class: "fa-#{mr[:icon]} fa missing_review"), main_app.request_show_path(request[:number])

app/views/obs_factory/staging_projects/show.html.erb
<% project_bread_crumb link_to('Staging projects', staging_projects_path(project: @distribution.name)), @staging_project.id %>

<div class="grid_13 alpha">

  <div class="box box-shadow" id="staging-detail">
    <h1><%= @staging_project.name %></h1>

    <h2>Packages</h2>

    <div id="packages-container">
      <%= render partial: 'packages_list', locals: { project: @staging_project } %>
      <div class="clearfix"></div>
    </div>

    <h2>Status</h2>
    <div class="factory-summary">
      <dl>
        <% ok = @staging_project.untracked_requests.size.zero? -%>
        <dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>Untracked requests</dt>
        <dd>
        <% if ok %>
          None.
        <% else %>
          <%= render @staging_project.untracked_requests %>
        <% end %>
        </dd>
        <% ok = @staging_project.obsolete_requests.size.zero? -%>
        <dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>Obsolete requests</dt>
        <dd>
        <% if ok %>
          None.
        <% else %>
          <%= render @staging_project.obsolete_requests %>
        <% end %>
        </dd>
        <% ok = @staging_project.missing_reviews.size.zero? -%>
        <dt><%= sprite_tag(ok ? 'accept' : 'error', alt: ok ? 'Ok' : 'Fail') %>Missing reviews</dt>
        <dd>
        <% if ok %>
          None.
        <% else %>
          <% missing = @staging_project.missing_reviews.map do |rev| %>
            <% link_to "#{rev[:package]} by #{rev[:by]}".html_safe, main_app.request_show_url(number: rev[:request]) %>
          <% end %>
          <%= missing.to_sentence.html_safe %>.
        <% end %>
        </dd>
        <%= render partial: 'buildinfo', locals: {project: @staging_project} %>
        <%= render partial: 'openqa_jobs', locals: {project: @staging_project} %>
      </dl>
      <% if @staging_project.subproject %>
        <h3>DVD subproject</h3>
        <dl>
          <%= render partial: 'buildinfo', locals: {project: @staging_project.subproject} %>
          <%= render partial: 'openqa_jobs', locals: {project: @staging_project.subproject} %>
        </dl>
      <% end %>
    </div>
  </div>
</div>

<div class="grid_3 omega">
  <%= render partial: 'legend'%>
</div>